from setuptools import setup, find_packages

setup(
    name="cot-priors",
    description="Reasoning priors of Chain-of-Thought in LLMs",
    author="Georgios Chochlakis",
    author_email="chochlak@usc.edu",
    packages=find_packages(),
    install_requires=[
        "torch",
        "transformers",
        "legm @ git+https://github.com/gchochla/legm.git@d4172f02c1364d05e780073380655b2929dddce8",
        "ember @ git+https://github.com/gchochla/ember.git@511490af69a5f03f5379f2e294b6df07ac6f980a",
        "gridparse @ git+https://github.com/gchochla/gridparse.git@598f40966e3bb8fc2b3170df094b2a8100c5b706",
        "langcodes",
        "language_data",
        "pandas",
        "scikit-learn",
        "openai",
        "tenacity",
        "python-dotenv",
        "ekphrasis",
        "accelerate",
        "bitsandbytes",
        "sentence-transformers",
        "matplotlib",
        "seaborn",
        "nltk",
        "gensim",
        "ai2-olmo",
        "datasets",
    ],
    extras_require={"dev": ["black", "pytest"]},
)
